version: '3.8'

services:
   postgres:
        image: postgres:latest
        container_name: postgres_layers_desafio
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - ./postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: layers
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: layers
            PGDATA: /var/lib/postgresql/data/pgdata